config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    get 'users/show'
    get 'users/sign_out' => 'devise/sessions#destroy'
  resources :posts do
      resources :comments
  end
  
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
          end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @comment = Comment.new
    end
    
    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.new
        @comment = @post.comments.create(params[:comment].permit(:user_id,:name, :comment ))
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to post_path(@post)
        end
        
    end
    
    
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
    
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        @post = Post.all.order("created_at DESC")
    end
    
    
    def new
        @post = Post.new
    end
    
    
    def create
        @post = Post.new(post_params)
        
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end
    
    
    def show
        @post = Post.find(params[:id])
    end
    
    
    def update
        @post = Post.find(params[:id])
        
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    
    def edit
        @post = Post.find(params[:id])
    end
    
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        redirect_to posts_path
    end
    
    
    private
    
    def post_params
        params.require(:post).permit(:title, :content, :image)
    end
    
    
    def find_post
        @post = Post.find(params[:id])
    end    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
    <article class="media">
        <div class="media-content">
            <div class="content">
                <p>
                    <strong><%= comment.user.name if comment.user  %>: </strong>
                    <%= comment.comment %>
                </p>
            </div>
        </div>
        
        <% if comment.user == current_user then %>
        <%= link_to "Delete", [comment.post, comment], 
        method: :delete, class: "button is-danger", data: { confirm: "Are you sure?" } %>
        <% end %>
    </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>

    <div class="field">
        <div class="control">
            <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-primary is-medium">
    <!-- Hero head: will stick at the top -->
    <div style="background-image:
    url('https://images.unsplash.com/photo-1432821596592-e2c18b78144f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YmxvZ3xlbnwwfHwwfHw%3D&w=1000&q=80');">
    <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to "Home", root_path, class: "button is-primary is-inverted" %>
              <span class="navbar-burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <% if user_signed_in? %>
                  <%= link_to "Create new post", new_post_path, class:"navbar-item" %>
                  <%= link_to current_user.name, users_show_path, class:"navbar-item" %>
                  <%= link_to "Logout", destroy_user_session_path, class:"navbar-item", method: :get %>
                <% else %>
                  <%= link_to "Register", new_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Login", new_user_session_path, class:"navbar-item" %>
                <% end %>
              </div>
            </div>
          </div>
        </nav>
    </div>


  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title" style="font-size: 60px">
          <%= yield :page_title %>
          <img src="https://www.pinclipart.com/picdir/big/51-511102_design-free-logo-srj-hd-logo-png-clipart.png" width="100" height="100" alt="Logo">
      </h1>
    </div>
  </div>

</section>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="selection">
    <%= simple_form_for @post do |f| %>
    <div class="field">
        <div class="control">
            <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    
    <div class="field">
        <div class="control">
            <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    
    <div class="field">
        <div class="control">
            <%= f.input :image, input_html: { class: 'file_field' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
   </div>
   
    <%= f.button :submit, class: "button is-primary" %>
    <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for:page_title, "Let's Blog" %>


<section class="section">
    <div class="container">
        <% @post.each do |post| %>
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="title is-4"> <%= link_to post.title, post %> </p>
                        </div>
                    </div>
                    <div class="content">
                        <%= post.content %>
                    </div>
                    <!-- <div class="comment-count">
                        <span class="tag is-rounded"><%# comment.count%></span>
                    </div> -->
                    
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/posts/new.html.erb
<% content_for:page_title,"Create new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for:page_title, @post.title %>

<section class="section">
    
    <div class="container">
        
        <div class="content">
            <div >
            <% if @post.image.attached? %>
                <%= image_tag @post.image %>
            <% end %>
            </div>
            
            <%= @post.content %>
            
        </div>
        
        
    </div>
</section>


<section class="section comment">
    <div class="container">
        <h2 class="subtitle is-5"><strong><%= @post.comments.count %> Comments </strong></h2>
        <%= render @post.comments %>
        
        <div class="comment-form">
            <hr />
            <h3 class="subtitle is-3">Leave a reply</h3>
            <% if user_signed_in? %>
                <%= render 'comments/form' %>
            <% else %>
                <%= link_to "Register", new_user_registration_path, class:"navbar-item" %>
                <%= link_to "Login", new_user_session_path, class:"navbar-item" %>
            <% end %>
        </div>
        
    </div>
</section>

app/views/users/show.html.erb
<div class="section">
  <div class="container is-flex is-justify-content-center">
    <div class="content is-medium is-narrow" style="width: 480px">
      <h2>User information</h2>
      <div class="form-inputs">
        <div class="field">
          <label class="label">Name</label>
          <div class="control">
            <input class="input" type="text" value=<%=@user.name%> disabled />
          </div>
        </div>
        <div class="field">
          <label class="label">Email</label>
          <div class="control">
            <input class="input" type="text" value=<%=@user.email%> disabled />
          </div>
        </div>
        <div style="font-size: 14px; text-align: left; margin-top: 16px">
          <span>
            <a href="/users/edit">Edit information</a>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>